[package]
name = "rust_vcs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.25", features = ["derive"] }
colored = "3.0.0"
pager = "0.16.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
sha2 = "0.10.8"
